# Generated by Django 3.1 on 2021-04-26 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('cpu', models.CharField(max_length=50)),
                ('screen_size', models.CharField(max_length=50)),
                ('ram', models.IntegerField()),
                ('color', models.CharField(choices=[('Blue', 'Blue'), ('Light blue', 'Light blue'), ('Mint', 'Mint'), ('Green', 'Green'), ('Light gree', 'Light green'), ('Yellow', 'Yellow'), ('Peach', 'Peach'), ('Orange', 'Orange'), ('Pink', 'Pink'), ('Red', 'Red'), ('Purple', 'Purple'), ('Violet', 'Violet'), ('Black', 'Black'), ('White', 'White')], default='', max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category')),
                ('mark', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.mark')),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
    ]
